// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs3Gpzz0mibugNE1vr73nldyXt1ZCtFyY',
    appId: '1:673695224591:android:d0803def6366f4fa0de47a',
    messagingSenderId: '673695224591',
    projectId: 'mdot-52f4d',
    databaseURL: 'https://mdot-52f4d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mdot-52f4d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKhzQPTx0_vdAX43EtJBTzfylWTIdRhDI',
    appId: '1:673695224591:ios:79fbd575f1d0b1000de47a',
    messagingSenderId: '673695224591',
    projectId: 'mdot-52f4d',
    databaseURL: 'https://mdot-52f4d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mdot-52f4d.appspot.com',
    iosClientId: '673695224591-f3lpk05fd8ed9vb97qkd8pu9l3rpbb53.apps.googleusercontent.com',
    iosBundleId: 'com.mdot.my',
  );
}
